/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import EDD.Names;
import EDD.Queue;
import Proyecto2_SO_Hurtado_Ruiz.Admin;
import Proyecto2_SO_Hurtado_Ruiz.IA;
import Proyecto2_SO_Hurtado_Ruiz.CharacterS;
import java.util.concurrent.Semaphore;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author José Hurtado & Joseph Ruiz
 */
public class Home extends javax.swing.JFrame {
    
    public static Admin admin;
    public static IA ia;
    public static Queue queueSW1;
    public static Queue queueSW2;
    public static Queue queueSW3;
    public static Queue queueSWR;
    
    public static Queue queueST1;
    public static Queue queueST2;
    public static Queue queueST3;
    public static Queue queueSTR;
    
    public static Semaphore mutex;
    
    public static JTextArea publicQueueSW1;
    public static JTextArea publicQueueSW2;
    public static JTextArea publicQueueSW3;
    public static JTextArea publicQueueSWR;
    
    public static JTextArea publicQueueST1;
    public static JTextArea publicQueueST2;
    public static JTextArea publicQueueST3;
    public static JTextArea publicQueueSTR;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Colas de Star Wars
        queueSW1 = new Queue();
        queueSW2 = new Queue();
        queueSW3 = new Queue();
        queueSWR = new Queue();
        //Colas de Star Trek
        queueST1 = new Queue();
        queueST2 = new Queue();
        queueST3 = new Queue();
        queueSTR = new Queue();
        mutex= new Semaphore(1);
        
        admin = new Admin(queueSW1, queueSW2, queueSW3, queueSWR, queueST1, queueST2, queueST3, queueSTR, mutex);
        ia= new IA(queueSW1, queueST1, queueSWR, queueSTR, fieldDaysMS, mutex);
        //Text areas pero públicos
        publicQueueSW1= pQueueSW1;
        publicQueueSW2= pQueueSW2;
        publicQueueSW3= pQueueSW3;
        publicQueueSWR= pQueueSWR;
        
        publicQueueST1= pQueueST1;
        publicQueueST2= pQueueST2;
        publicQueueST3= pQueueST3;
        publicQueueSTR= pQueueSTR;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        starwarsLogo = new javax.swing.JLabel();
        medal1 = new javax.swing.JLabel();
        Winner = new javax.swing.JLabel();
        medal2 = new javax.swing.JLabel();
        starTrekLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        victoriesST = new javax.swing.JLabel();
        aiImage1 = new javax.swing.JLabel();
        aiState1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldDaysMS = new javax.swing.JTextField();
        victoriesSW1 = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        speedSim = new javax.swing.JLabel();
        victoriesST1 = new javax.swing.JLabel();
        vs1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        pQueueSW1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        pQueueSW2 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        pQueueSW3 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        pQueueSWR = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        pQueueST1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        pQueueST3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pQueueST2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        pQueueSTR = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane16.setViewportView(jTextArea5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 38, 99));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        starwarsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dg7eops-ddf01d9a-a419-42c8-9698-0fa0d6527e6b (2).png"))); // NOI18N
        jPanel1.add(starwarsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 150, 80));

        medal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/badge-outline-filled (1).png"))); // NOI18N
        medal1.setText("jLabel4");
        jPanel1.add(medal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 50, 50));

        Winner.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Winner.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        Winner.setText("Winner!!");
        jPanel1.add(Winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 80, -1));

        medal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/badge-outline-filled (1).png"))); // NOI18N
        medal2.setText("jLabel4");
        jPanel1.add(medal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        starTrekLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/image_2024-10-22_185537482-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(starTrekLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cola P1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Cola P2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Cola P1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cola P2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Cola P3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Refuerzo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Refuerzo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cola P3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));

        victoriesST.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        victoriesST.setForeground(new java.awt.Color(255, 255, 255));
        victoriesST.setText("Ganador");
        jPanel1.add(victoriesST, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 160, 50));

        aiImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1f916 (1).png"))); // NOI18N
        aiImage1.setText("jLabel2");
        jPanel1.add(aiImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 90, 110));

        aiState1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        aiState1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        aiState1.setText("Waiting");
        jPanel1.add(aiState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 70, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(220, 223, 219));
        jLabel9.setText("Made by Hurtado, José & Ruiz, Joseph ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        fieldDaysMS.setBackground(new java.awt.Color(50, 48, 157));
        fieldDaysMS.setForeground(new java.awt.Color(255, 255, 255));
        fieldDaysMS.setText("1000");
        fieldDaysMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDaysMSActionPerformed(evt);
            }
        });
        jPanel1.add(fieldDaysMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 70, 30));

        victoriesSW1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        victoriesSW1.setForeground(new java.awt.Color(255, 255, 255));
        victoriesSW1.setText("0");
        jPanel1.add(victoriesSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 30, 50));

        vs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/png-clipart-vs-match-vs-game-thumbnail-removebg-preview (1)_1.png"))); // NOI18N
        jPanel1.add(vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, 80));

        speedSim.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        speedSim.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        speedSim.setText("Velocidad");
        jPanel1.add(speedSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 90, -1));

        victoriesST1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        victoriesST1.setForeground(new java.awt.Color(255, 255, 255));
        victoriesST1.setText("0");
        jPanel1.add(victoriesST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 30, 50));

        vs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/png-clipart-vs-match-vs-game-thumbnail-removebg-preview (1)_1.png"))); // NOI18N
        jPanel1.add(vs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 150, 80));

        startButton.setText("INICIAR");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 77, -1));

        pQueueSW1.setBackground(new java.awt.Color(50, 48, 157));
        pQueueSW1.setColumns(20);
        pQueueSW1.setForeground(new java.awt.Color(255, 255, 255));
        pQueueSW1.setRows(5);
        pQueueSW1.setCaretColor(new java.awt.Color(255, 255, 255));
        pQueueSW1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane9.setViewportView(pQueueSW1);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 120, 120));

        pQueueSW2.setBackground(new java.awt.Color(50, 48, 157));
        pQueueSW2.setColumns(20);
        pQueueSW2.setForeground(new java.awt.Color(255, 255, 255));
        pQueueSW2.setRows(5);
        pQueueSW2.setCaretColor(new java.awt.Color(255, 255, 255));
        pQueueSW2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane12.setViewportView(pQueueSW2);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 120, 120));

        pQueueSW3.setBackground(new java.awt.Color(50, 48, 157));
        pQueueSW3.setColumns(20);
        pQueueSW3.setForeground(new java.awt.Color(255, 255, 255));
        pQueueSW3.setRows(5);
        pQueueSW3.setCaretColor(new java.awt.Color(255, 255, 255));
        pQueueSW3.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane14.setViewportView(pQueueSW3);

        jPanel1.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 120, 120));

        pQueueSWR.setBackground(new java.awt.Color(50, 48, 157));
        pQueueSWR.setColumns(20);
        pQueueSWR.setForeground(new java.awt.Color(255, 255, 255));
        pQueueSWR.setRows(5);
        pQueueSWR.setCaretColor(new java.awt.Color(255, 255, 255));
        pQueueSWR.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane17.setViewportView(pQueueSWR);

        jPanel1.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 120, 120));

        pQueueST1.setBackground(new java.awt.Color(50, 48, 157));
        pQueueST1.setColumns(20);
        pQueueST1.setForeground(new java.awt.Color(255, 255, 255));
        pQueueST1.setRows(5);
        jScrollPane1.setViewportView(pQueueST1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 120));

        pQueueST3.setBackground(new java.awt.Color(50, 48, 157));
        pQueueST3.setColumns(20);
        pQueueST3.setForeground(new java.awt.Color(255, 255, 255));
        pQueueST3.setRows(5);
        jScrollPane3.setViewportView(pQueueST3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, 120));

        pQueueST2.setBackground(new java.awt.Color(50, 48, 157));
        pQueueST2.setColumns(20);
        pQueueST2.setForeground(new java.awt.Color(255, 255, 255));
        pQueueST2.setRows(5);
        jScrollPane2.setViewportView(pQueueST2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 120));

        pQueueSTR.setBackground(new java.awt.Color(50, 48, 157));
        pQueueSTR.setColumns(20);
        pQueueSTR.setForeground(new java.awt.Color(255, 255, 255));
        pQueueSTR.setRows(5);
        jScrollPane4.setViewportView(pQueueSTR);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 120, 120));

        background.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/146610-large-star-wars-star-background-1920x1080 (2).jpg"))); // NOI18N
        background.setText("0");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        jTextArea2.setBackground(new java.awt.Color(50, 48, 157));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane13.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 120, 120));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane15.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 120, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDaysMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDaysMSActionPerformed
        //dayMS=Integer.parseInt(fieldDaysMS.getText());
    }//GEN-LAST:event_fieldDaysMSActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        admin.StartSimulation();
        JOptionPane.showMessageDialog(null, "Personajes agregados a sus colas");
        startButton.setVisible(false);        
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Winner;
    private javax.swing.JLabel aiImage1;
    private javax.swing.JLabel aiState1;
    private javax.swing.JLabel background;
    private javax.swing.JTextField fieldDaysMS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel medal1;
    private javax.swing.JLabel medal2;
    private javax.swing.JTextArea pQueueST1;
    private javax.swing.JTextArea pQueueST2;
    private javax.swing.JTextArea pQueueST3;
    private javax.swing.JTextArea pQueueSTR;
    private javax.swing.JTextArea pQueueSW1;
    private javax.swing.JTextArea pQueueSW2;
    private javax.swing.JTextArea pQueueSW3;
    private javax.swing.JTextArea pQueueSWR;
    private javax.swing.JLabel speedSim;
    private javax.swing.JLabel starTrekLogo;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel starwarsLogo;
    private javax.swing.JLabel victoriesST;
    private javax.swing.JLabel victoriesST1;
    private javax.swing.JLabel victoriesSW1;
    private javax.swing.JLabel vs;
    private javax.swing.JLabel vs1;
    // End of variables declaration//GEN-END:variables
}
